import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";
import ScrollToTop from "@/Components/ScrollTop";
import WhatsAppIcon from "@/Components/WhatsappIcon";
import Footer from "@/Components/Footer";
import ChatbotComponent from "@/chatbot/ChatbotComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Jadeed Soft Technologies",
    template: "%s - Jadeed Soft Technologies",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <link
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
    rel="stylesheet"
/> */}

      <body className={`${inter.className} scroll-smooth`}>
        <Header />
        {children}
        <ScrollToTop />
        <ChatbotComponent />
        <WhatsAppIcon />
        <Footer />
      </body>
    </html>
  );
}
